// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6z1c9EE4PkJC3guUbZvwff
// Component: DHaCrsySHZ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 6z1c9EE4PkJC3guUbZvwff/projectcss
import sty from "./PlasmicStandardLink.module.css"; // plasmic-import: DHaCrsySHZ/css

export type PlasmicStandardLink__VariantMembers = {};

export type PlasmicStandardLink__VariantsArgs = {};
type VariantPropType = keyof PlasmicStandardLink__VariantsArgs;
export const PlasmicStandardLink__VariantProps = new Array<VariantPropType>();

export type PlasmicStandardLink__ArgsType = {};
type ArgPropType = keyof PlasmicStandardLink__ArgsType;
export const PlasmicStandardLink__ArgProps = new Array<ArgPropType>();

export type PlasmicStandardLink__OverridesType = {
  root?: p.Flex<"h1">;
};

export interface DefaultStandardLinkProps {
  className?: string;
}

function PlasmicStandardLink__RenderFunc(props: {
  variants: PlasmicStandardLink__VariantsArgs;
  args: PlasmicStandardLink__ArgsType;
  overrides: PlasmicStandardLink__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <h1
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.h1,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        sty.root
      )}
    >
      {"111111111111111\n1111\n1\n\n1111\n"}
    </h1>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStandardLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStandardLink__VariantsArgs;
    args?: PlasmicStandardLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStandardLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicStandardLink__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicStandardLink__ArgProps,
      internalVariantPropNames: PlasmicStandardLink__VariantProps
    });

    return PlasmicStandardLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStandardLink";
  } else {
    func.displayName = `PlasmicStandardLink.${nodeName}`;
  }
  return func;
}

export const PlasmicStandardLink = Object.assign(
  // Top-level PlasmicStandardLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStandardLink
    internalVariantProps: PlasmicStandardLink__VariantProps,
    internalArgProps: PlasmicStandardLink__ArgProps
  }
);

export default PlasmicStandardLink;
/* prettier-ignore-end */
