// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicFab, DefaultFabProps } from "./plasmic/minitwitter/PlasmicFab";
import { Link } from "react-router-dom";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface FabProps extends DefaultFabProps {}

function Fab_(props: FabProps, ref: HTMLElementRefOf<"a">) {
  return (
    <PlasmicFab
      {...props}
      root={{
        as: Link,
        props: {
          to: "/post",
        },
      }}
    />
  );
}

const Fab = React.forwardRef(Fab_);
export default Fab;
