// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicNewPost,
  DefaultNewPostProps,
} from "./plasmic/minitwitter/PlasmicNewPost";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { createPost, PostEntry } from "../model";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export interface NewPostProps extends DefaultNewPostProps {
  children?: never;
  onAdd: (entry: PostEntry) => void;
}

function NewPost_(
  { onAdd, ...rest }: NewPostProps,
  ref: HTMLElementRefOf<"div">
) {
  const [content, setContent] = useState("");
  const navigate = useNavigate();

  return (
    <PlasmicNewPost
      {...rest}
      postContent={{
        autoFocus: true,
        value: content,
        onChange: (e) => {
          setContent(e.target.value);
        },
      }}
      postButton={{
        onClick: () => {
          onAdd(
            createPost({
              content,
              createdAt: new Date(),
            })
          );
          navigate("/");
        },
      }}
    />
  );
}

const NewPost = React.forwardRef(NewPost_);
export default NewPost;
